server:
  port: 1112

spring:
  application:
    name: gr-springboot-swagger-openapi-squeleton
  profiles:
    active: local
#  cloud:
#    config:
#      uri: http://localhost:8762
#      fail-fast: true
#      retry:
#        max-attempts: 6
#        initial-interval: 1000
#        max-interval: 2000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true
  
# http://localhost:1112/swagger-ui/index.html
app:
  openapi:
    dev-url: http://localhost:${server.port}
    homol-url: http://10.0.0.137:${server.port}
    prod-url: https://prod-url.com